---

- name: Update packages
  apt:
    update_cache: yes
    upgrade: yes

# - name: Reboot
#   changed_when: false
#   reboot:
#     reboot_timeout: 200

- name: Install packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - ffmpeg
    - v4l2loopback-dkms

- name: Enable v4l2loopback module
  copy:
    dest: "/etc/modules-load.d/v4l2loopback.conf"
    content: "v4l2loopback"

- name: Set loopback file /dev/video99
  copy:
    dest: "/etc/modprobe.d/v4l2loopback.conf"
    content: "options v4l2loopback video_nr=99"
